/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginDevRouteImport } from './routes/login-dev'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppObrigacoesRouteImport } from './routes/_app.obrigacoes'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppFiscalIndexRouteImport } from './routes/_app.fiscal.index'
import { Route as ApiWaInstancesRouteImport } from './routes/api/wa/instances'
import { Route as AppFiscalSerproRouteImport } from './routes/_app.fiscal.serpro'
import { Route as AppFiscalNfseRouteImport } from './routes/_app.fiscal.nfse'
import { Route as AppFiscalDasRouteImport } from './routes/_app.fiscal.das'
import { Route as AppConfiguracoesServicosRouteImport } from './routes/_app.configuracoes_.servicos'
import { Route as AppClientesIdRouteImport } from './routes/_app.clientes_.$id'
import { Route as ApiPublicEvolutionWebhookInstanceRouteImport } from './routes/api/public/evolution-webhook.$instance'

const LoginDevRoute = LoginDevRouteImport.update({
  id: '/login-dev',
  path: '/login-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppObrigacoesRoute = AppObrigacoesRouteImport.update({
  id: '/obrigacoes',
  path: '/obrigacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalIndexRoute = AppFiscalIndexRouteImport.update({
  id: '/fiscal/',
  path: '/fiscal/',
  getParentRoute: () => AppRoute,
} as any)
const ApiWaInstancesRoute = ApiWaInstancesRouteImport.update({
  id: '/api/wa/instances',
  path: '/api/wa/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFiscalSerproRoute = AppFiscalSerproRouteImport.update({
  id: '/fiscal/serpro',
  path: '/fiscal/serpro',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalNfseRoute = AppFiscalNfseRouteImport.update({
  id: '/fiscal/nfse',
  path: '/fiscal/nfse',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalDasRoute = AppFiscalDasRouteImport.update({
  id: '/fiscal/das',
  path: '/fiscal/das',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesServicosRoute =
  AppConfiguracoesServicosRouteImport.update({
    id: '/configuracoes_/servicos',
    path: '/configuracoes/servicos',
    getParentRoute: () => AppRoute,
  } as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes_/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicEvolutionWebhookInstanceRoute =
  ApiPublicEvolutionWebhookInstanceRouteImport.update({
    id: '/api/public/evolution-webhook/$instance',
    path: '/api/public/evolution-webhook/$instance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/login-dev': typeof LoginDevRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/obrigacoes': typeof AppObrigacoesRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/configuracoes/servicos': typeof AppConfiguracoesServicosRoute
  '/fiscal/das': typeof AppFiscalDasRoute
  '/fiscal/nfse': typeof AppFiscalNfseRoute
  '/fiscal/serpro': typeof AppFiscalSerproRoute
  '/api/wa/instances': typeof ApiWaInstancesRoute
  '/fiscal/': typeof AppFiscalIndexRoute
  '/api/public/evolution-webhook/$instance': typeof ApiPublicEvolutionWebhookInstanceRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/login-dev': typeof LoginDevRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/obrigacoes': typeof AppObrigacoesRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/': typeof AppIndexRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/configuracoes/servicos': typeof AppConfiguracoesServicosRoute
  '/fiscal/das': typeof AppFiscalDasRoute
  '/fiscal/nfse': typeof AppFiscalNfseRoute
  '/fiscal/serpro': typeof AppFiscalSerproRoute
  '/api/wa/instances': typeof ApiWaInstancesRoute
  '/fiscal': typeof AppFiscalIndexRoute
  '/api/public/evolution-webhook/$instance': typeof ApiPublicEvolutionWebhookInstanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/login-dev': typeof LoginDevRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/obrigacoes': typeof AppObrigacoesRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clientes_/$id': typeof AppClientesIdRoute
  '/_app/configuracoes_/servicos': typeof AppConfiguracoesServicosRoute
  '/_app/fiscal/das': typeof AppFiscalDasRoute
  '/_app/fiscal/nfse': typeof AppFiscalNfseRoute
  '/_app/fiscal/serpro': typeof AppFiscalSerproRoute
  '/api/wa/instances': typeof ApiWaInstancesRoute
  '/_app/fiscal/': typeof AppFiscalIndexRoute
  '/api/public/evolution-webhook/$instance': typeof ApiPublicEvolutionWebhookInstanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login-dev'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/obrigacoes'
    | '/whatsapp'
    | '/clientes/$id'
    | '/configuracoes/servicos'
    | '/fiscal/das'
    | '/fiscal/nfse'
    | '/fiscal/serpro'
    | '/api/wa/instances'
    | '/fiscal/'
    | '/api/public/evolution-webhook/$instance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/login-dev'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/obrigacoes'
    | '/whatsapp'
    | '/'
    | '/clientes/$id'
    | '/configuracoes/servicos'
    | '/fiscal/das'
    | '/fiscal/nfse'
    | '/fiscal/serpro'
    | '/api/wa/instances'
    | '/fiscal'
    | '/api/public/evolution-webhook/$instance'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/login-dev'
    | '/_app/clientes'
    | '/_app/configuracoes'
    | '/_app/financeiro'
    | '/_app/obrigacoes'
    | '/_app/whatsapp'
    | '/_app/'
    | '/_app/clientes_/$id'
    | '/_app/configuracoes_/servicos'
    | '/_app/fiscal/das'
    | '/_app/fiscal/nfse'
    | '/_app/fiscal/serpro'
    | '/api/wa/instances'
    | '/_app/fiscal/'
    | '/api/public/evolution-webhook/$instance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginDevRoute: typeof LoginDevRoute
  ApiWaInstancesRoute: typeof ApiWaInstancesRoute
  ApiPublicEvolutionWebhookInstanceRoute: typeof ApiPublicEvolutionWebhookInstanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-dev': {
      id: '/login-dev'
      path: '/login-dev'
      fullPath: '/login-dev'
      preLoaderRoute: typeof LoginDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obrigacoes': {
      id: '/_app/obrigacoes'
      path: '/obrigacoes'
      fullPath: '/obrigacoes'
      preLoaderRoute: typeof AppObrigacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/': {
      id: '/_app/fiscal/'
      path: '/fiscal'
      fullPath: '/fiscal/'
      preLoaderRoute: typeof AppFiscalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/wa/instances': {
      id: '/api/wa/instances'
      path: '/api/wa/instances'
      fullPath: '/api/wa/instances'
      preLoaderRoute: typeof ApiWaInstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/fiscal/serpro': {
      id: '/_app/fiscal/serpro'
      path: '/fiscal/serpro'
      fullPath: '/fiscal/serpro'
      preLoaderRoute: typeof AppFiscalSerproRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/nfse': {
      id: '/_app/fiscal/nfse'
      path: '/fiscal/nfse'
      fullPath: '/fiscal/nfse'
      preLoaderRoute: typeof AppFiscalNfseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/das': {
      id: '/_app/fiscal/das'
      path: '/fiscal/das'
      fullPath: '/fiscal/das'
      preLoaderRoute: typeof AppFiscalDasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes_/servicos': {
      id: '/_app/configuracoes_/servicos'
      path: '/configuracoes/servicos'
      fullPath: '/configuracoes/servicos'
      preLoaderRoute: typeof AppConfiguracoesServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes_/$id': {
      id: '/_app/clientes_/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/evolution-webhook/$instance': {
      id: '/api/public/evolution-webhook/$instance'
      path: '/api/public/evolution-webhook/$instance'
      fullPath: '/api/public/evolution-webhook/$instance'
      preLoaderRoute: typeof ApiPublicEvolutionWebhookInstanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppObrigacoesRoute: typeof AppObrigacoesRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppConfiguracoesServicosRoute: typeof AppConfiguracoesServicosRoute
  AppFiscalDasRoute: typeof AppFiscalDasRoute
  AppFiscalNfseRoute: typeof AppFiscalNfseRoute
  AppFiscalSerproRoute: typeof AppFiscalSerproRoute
  AppFiscalIndexRoute: typeof AppFiscalIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppObrigacoesRoute: AppObrigacoesRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppConfiguracoesServicosRoute: AppConfiguracoesServicosRoute,
  AppFiscalDasRoute: AppFiscalDasRoute,
  AppFiscalNfseRoute: AppFiscalNfseRoute,
  AppFiscalSerproRoute: AppFiscalSerproRoute,
  AppFiscalIndexRoute: AppFiscalIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginDevRoute: LoginDevRoute,
  ApiWaInstancesRoute: ApiWaInstancesRoute,
  ApiPublicEvolutionWebhookInstanceRoute:
    ApiPublicEvolutionWebhookInstanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
