/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginDevRouteImport } from './routes/login-dev'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as AppWorkflowsRouteImport } from './routes/_app.workflows'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppSocietarioRouteImport } from './routes/_app.societario'
import { Route as AppObrigacoesRouteImport } from './routes/_app.obrigacoes'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppDpRouteImport } from './routes/_app.dp'
import { Route as AppDocumentosRouteImport } from './routes/_app.documentos'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppContabilRouteImport } from './routes/_app.contabil'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppAutomacoesRouteImport } from './routes/_app.automacoes'
import { Route as ApiNfseIndexRouteImport } from './routes/api/nfse/index'
import { Route as AppFiscalIndexRouteImport } from './routes/_app.fiscal.index'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'
import { Route as ApiWhatsappModoHumanoRouteImport } from './routes/api/whatsapp/modo-humano'
import { Route as ApiWaSendRouteImport } from './routes/api/wa/send'
import { Route as ApiWaInstancesRouteImport } from './routes/api/wa/instances'
import { Route as ApiUsuariosConvidarRouteImport } from './routes/api/usuarios/convidar'
import { Route as ApiSerproStatusRouteImport } from './routes/api/serpro/status'
import { Route as ApiSerproCallRouteImport } from './routes/api/serpro/call'
import { Route as ApiDasGerarRouteImport } from './routes/api/das/gerar'
import { Route as ApiCobrancaWebhookRouteImport } from './routes/api/cobranca/webhook'
import { Route as ApiCobrancaSetupWebhookRouteImport } from './routes/api/cobranca/setup-webhook'
import { Route as ApiCobrancaReguaRouteImport } from './routes/api/cobranca/regua'
import { Route as ApiCobrancaEmitirRouteImport } from './routes/api/cobranca/emitir'
import { Route as ApiCheckoutIdRouteImport } from './routes/api/checkout/$id'
import { Route as AppFiscalSerproRouteImport } from './routes/_app.fiscal.serpro'
import { Route as AppFiscalNfseRouteImport } from './routes/_app.fiscal.nfse'
import { Route as AppFiscalDasRouteImport } from './routes/_app.fiscal.das'
import { Route as AppDpEmpresaIdRouteImport } from './routes/_app.dp_.$empresaId'
import { Route as AppConfiguracoesServicosRouteImport } from './routes/_app.configuracoes_.servicos'
import { Route as AppClientesIdRouteImport } from './routes/_app.clientes_.$id'
import { Route as ApiPublicEvolutionWebhookInstanceRouteImport } from './routes/api/public/evolution-webhook.$instance'

const LoginDevRoute = LoginDevRouteImport.update({
  id: '/login-dev',
  path: '/login-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppSocietarioRoute = AppSocietarioRouteImport.update({
  id: '/societario',
  path: '/societario',
  getParentRoute: () => AppRoute,
} as any)
const AppObrigacoesRoute = AppObrigacoesRouteImport.update({
  id: '/obrigacoes',
  path: '/obrigacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDpRoute = AppDpRouteImport.update({
  id: '/dp',
  path: '/dp',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppContabilRoute = AppContabilRouteImport.update({
  id: '/contabil',
  path: '/contabil',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const ApiNfseIndexRoute = ApiNfseIndexRouteImport.update({
  id: '/api/nfse/',
  path: '/api/nfse/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFiscalIndexRoute = AppFiscalIndexRouteImport.update({
  id: '/fiscal/',
  path: '/fiscal/',
  getParentRoute: () => AppRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappModoHumanoRoute = ApiWhatsappModoHumanoRouteImport.update({
  id: '/api/whatsapp/modo-humano',
  path: '/api/whatsapp/modo-humano',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaSendRoute = ApiWaSendRouteImport.update({
  id: '/api/wa/send',
  path: '/api/wa/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaInstancesRoute = ApiWaInstancesRouteImport.update({
  id: '/api/wa/instances',
  path: '/api/wa/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsuariosConvidarRoute = ApiUsuariosConvidarRouteImport.update({
  id: '/api/usuarios/convidar',
  path: '/api/usuarios/convidar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSerproStatusRoute = ApiSerproStatusRouteImport.update({
  id: '/api/serpro/status',
  path: '/api/serpro/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSerproCallRoute = ApiSerproCallRouteImport.update({
  id: '/api/serpro/call',
  path: '/api/serpro/call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDasGerarRoute = ApiDasGerarRouteImport.update({
  id: '/api/das/gerar',
  path: '/api/das/gerar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCobrancaWebhookRoute = ApiCobrancaWebhookRouteImport.update({
  id: '/api/cobranca/webhook',
  path: '/api/cobranca/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCobrancaSetupWebhookRoute = ApiCobrancaSetupWebhookRouteImport.update({
  id: '/api/cobranca/setup-webhook',
  path: '/api/cobranca/setup-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCobrancaReguaRoute = ApiCobrancaReguaRouteImport.update({
  id: '/api/cobranca/regua',
  path: '/api/cobranca/regua',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCobrancaEmitirRoute = ApiCobrancaEmitirRouteImport.update({
  id: '/api/cobranca/emitir',
  path: '/api/cobranca/emitir',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutIdRoute = ApiCheckoutIdRouteImport.update({
  id: '/api/checkout/$id',
  path: '/api/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFiscalSerproRoute = AppFiscalSerproRouteImport.update({
  id: '/fiscal/serpro',
  path: '/fiscal/serpro',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalNfseRoute = AppFiscalNfseRouteImport.update({
  id: '/fiscal/nfse',
  path: '/fiscal/nfse',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalDasRoute = AppFiscalDasRouteImport.update({
  id: '/fiscal/das',
  path: '/fiscal/das',
  getParentRoute: () => AppRoute,
} as any)
const AppDpEmpresaIdRoute = AppDpEmpresaIdRouteImport.update({
  id: '/dp_/$empresaId',
  path: '/dp/$empresaId',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesServicosRoute =
  AppConfiguracoesServicosRouteImport.update({
    id: '/configuracoes_/servicos',
    path: '/configuracoes/servicos',
    getParentRoute: () => AppRoute,
  } as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes_/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicEvolutionWebhookInstanceRoute =
  ApiPublicEvolutionWebhookInstanceRouteImport.update({
    id: '/api/public/evolution-webhook/$instance',
    path: '/api/public/evolution-webhook/$instance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/login-dev': typeof LoginDevRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contabil': typeof AppContabilRoute
  '/crm': typeof AppCrmRoute
  '/documentos': typeof AppDocumentosRoute
  '/dp': typeof AppDpRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/obrigacoes': typeof AppObrigacoesRoute
  '/societario': typeof AppSocietarioRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/workflows': typeof AppWorkflowsRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/configuracoes/servicos': typeof AppConfiguracoesServicosRoute
  '/dp/$empresaId': typeof AppDpEmpresaIdRoute
  '/fiscal/das': typeof AppFiscalDasRoute
  '/fiscal/nfse': typeof AppFiscalNfseRoute
  '/fiscal/serpro': typeof AppFiscalSerproRoute
  '/api/checkout/$id': typeof ApiCheckoutIdRoute
  '/api/cobranca/emitir': typeof ApiCobrancaEmitirRoute
  '/api/cobranca/regua': typeof ApiCobrancaReguaRoute
  '/api/cobranca/setup-webhook': typeof ApiCobrancaSetupWebhookRoute
  '/api/cobranca/webhook': typeof ApiCobrancaWebhookRoute
  '/api/das/gerar': typeof ApiDasGerarRoute
  '/api/serpro/call': typeof ApiSerproCallRoute
  '/api/serpro/status': typeof ApiSerproStatusRoute
  '/api/usuarios/convidar': typeof ApiUsuariosConvidarRoute
  '/api/wa/instances': typeof ApiWaInstancesRoute
  '/api/wa/send': typeof ApiWaSendRoute
  '/api/whatsapp/modo-humano': typeof ApiWhatsappModoHumanoRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/fiscal/': typeof AppFiscalIndexRoute
  '/api/nfse/': typeof ApiNfseIndexRoute
  '/api/public/evolution-webhook/$instance': typeof ApiPublicEvolutionWebhookInstanceRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/login-dev': typeof LoginDevRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contabil': typeof AppContabilRoute
  '/crm': typeof AppCrmRoute
  '/documentos': typeof AppDocumentosRoute
  '/dp': typeof AppDpRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/obrigacoes': typeof AppObrigacoesRoute
  '/societario': typeof AppSocietarioRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/workflows': typeof AppWorkflowsRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/': typeof AppIndexRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/configuracoes/servicos': typeof AppConfiguracoesServicosRoute
  '/dp/$empresaId': typeof AppDpEmpresaIdRoute
  '/fiscal/das': typeof AppFiscalDasRoute
  '/fiscal/nfse': typeof AppFiscalNfseRoute
  '/fiscal/serpro': typeof AppFiscalSerproRoute
  '/api/checkout/$id': typeof ApiCheckoutIdRoute
  '/api/cobranca/emitir': typeof ApiCobrancaEmitirRoute
  '/api/cobranca/regua': typeof ApiCobrancaReguaRoute
  '/api/cobranca/setup-webhook': typeof ApiCobrancaSetupWebhookRoute
  '/api/cobranca/webhook': typeof ApiCobrancaWebhookRoute
  '/api/das/gerar': typeof ApiDasGerarRoute
  '/api/serpro/call': typeof ApiSerproCallRoute
  '/api/serpro/status': typeof ApiSerproStatusRoute
  '/api/usuarios/convidar': typeof ApiUsuariosConvidarRoute
  '/api/wa/instances': typeof ApiWaInstancesRoute
  '/api/wa/send': typeof ApiWaSendRoute
  '/api/whatsapp/modo-humano': typeof ApiWhatsappModoHumanoRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/fiscal': typeof AppFiscalIndexRoute
  '/api/nfse': typeof ApiNfseIndexRoute
  '/api/public/evolution-webhook/$instance': typeof ApiPublicEvolutionWebhookInstanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/login-dev': typeof LoginDevRoute
  '/_app/automacoes': typeof AppAutomacoesRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contabil': typeof AppContabilRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/documentos': typeof AppDocumentosRoute
  '/_app/dp': typeof AppDpRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/obrigacoes': typeof AppObrigacoesRoute
  '/_app/societario': typeof AppSocietarioRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/workflows': typeof AppWorkflowsRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clientes_/$id': typeof AppClientesIdRoute
  '/_app/configuracoes_/servicos': typeof AppConfiguracoesServicosRoute
  '/_app/dp_/$empresaId': typeof AppDpEmpresaIdRoute
  '/_app/fiscal/das': typeof AppFiscalDasRoute
  '/_app/fiscal/nfse': typeof AppFiscalNfseRoute
  '/_app/fiscal/serpro': typeof AppFiscalSerproRoute
  '/api/checkout/$id': typeof ApiCheckoutIdRoute
  '/api/cobranca/emitir': typeof ApiCobrancaEmitirRoute
  '/api/cobranca/regua': typeof ApiCobrancaReguaRoute
  '/api/cobranca/setup-webhook': typeof ApiCobrancaSetupWebhookRoute
  '/api/cobranca/webhook': typeof ApiCobrancaWebhookRoute
  '/api/das/gerar': typeof ApiDasGerarRoute
  '/api/serpro/call': typeof ApiSerproCallRoute
  '/api/serpro/status': typeof ApiSerproStatusRoute
  '/api/usuarios/convidar': typeof ApiUsuariosConvidarRoute
  '/api/wa/instances': typeof ApiWaInstancesRoute
  '/api/wa/send': typeof ApiWaSendRoute
  '/api/whatsapp/modo-humano': typeof ApiWhatsappModoHumanoRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/_app/fiscal/': typeof AppFiscalIndexRoute
  '/api/nfse/': typeof ApiNfseIndexRoute
  '/api/public/evolution-webhook/$instance': typeof ApiPublicEvolutionWebhookInstanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login-dev'
    | '/automacoes'
    | '/clientes'
    | '/configuracoes'
    | '/contabil'
    | '/crm'
    | '/documentos'
    | '/dp'
    | '/financeiro'
    | '/obrigacoes'
    | '/societario'
    | '/whatsapp'
    | '/workflows'
    | '/checkout/$id'
    | '/clientes/$id'
    | '/configuracoes/servicos'
    | '/dp/$empresaId'
    | '/fiscal/das'
    | '/fiscal/nfse'
    | '/fiscal/serpro'
    | '/api/checkout/$id'
    | '/api/cobranca/emitir'
    | '/api/cobranca/regua'
    | '/api/cobranca/setup-webhook'
    | '/api/cobranca/webhook'
    | '/api/das/gerar'
    | '/api/serpro/call'
    | '/api/serpro/status'
    | '/api/usuarios/convidar'
    | '/api/wa/instances'
    | '/api/wa/send'
    | '/api/whatsapp/modo-humano'
    | '/api/whatsapp/webhook'
    | '/fiscal/'
    | '/api/nfse/'
    | '/api/public/evolution-webhook/$instance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/login-dev'
    | '/automacoes'
    | '/clientes'
    | '/configuracoes'
    | '/contabil'
    | '/crm'
    | '/documentos'
    | '/dp'
    | '/financeiro'
    | '/obrigacoes'
    | '/societario'
    | '/whatsapp'
    | '/workflows'
    | '/checkout/$id'
    | '/'
    | '/clientes/$id'
    | '/configuracoes/servicos'
    | '/dp/$empresaId'
    | '/fiscal/das'
    | '/fiscal/nfse'
    | '/fiscal/serpro'
    | '/api/checkout/$id'
    | '/api/cobranca/emitir'
    | '/api/cobranca/regua'
    | '/api/cobranca/setup-webhook'
    | '/api/cobranca/webhook'
    | '/api/das/gerar'
    | '/api/serpro/call'
    | '/api/serpro/status'
    | '/api/usuarios/convidar'
    | '/api/wa/instances'
    | '/api/wa/send'
    | '/api/whatsapp/modo-humano'
    | '/api/whatsapp/webhook'
    | '/fiscal'
    | '/api/nfse'
    | '/api/public/evolution-webhook/$instance'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/login-dev'
    | '/_app/automacoes'
    | '/_app/clientes'
    | '/_app/configuracoes'
    | '/_app/contabil'
    | '/_app/crm'
    | '/_app/documentos'
    | '/_app/dp'
    | '/_app/financeiro'
    | '/_app/obrigacoes'
    | '/_app/societario'
    | '/_app/whatsapp'
    | '/_app/workflows'
    | '/checkout/$id'
    | '/_app/'
    | '/_app/clientes_/$id'
    | '/_app/configuracoes_/servicos'
    | '/_app/dp_/$empresaId'
    | '/_app/fiscal/das'
    | '/_app/fiscal/nfse'
    | '/_app/fiscal/serpro'
    | '/api/checkout/$id'
    | '/api/cobranca/emitir'
    | '/api/cobranca/regua'
    | '/api/cobranca/setup-webhook'
    | '/api/cobranca/webhook'
    | '/api/das/gerar'
    | '/api/serpro/call'
    | '/api/serpro/status'
    | '/api/usuarios/convidar'
    | '/api/wa/instances'
    | '/api/wa/send'
    | '/api/whatsapp/modo-humano'
    | '/api/whatsapp/webhook'
    | '/_app/fiscal/'
    | '/api/nfse/'
    | '/api/public/evolution-webhook/$instance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginDevRoute: typeof LoginDevRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  ApiCheckoutIdRoute: typeof ApiCheckoutIdRoute
  ApiCobrancaEmitirRoute: typeof ApiCobrancaEmitirRoute
  ApiCobrancaReguaRoute: typeof ApiCobrancaReguaRoute
  ApiCobrancaSetupWebhookRoute: typeof ApiCobrancaSetupWebhookRoute
  ApiCobrancaWebhookRoute: typeof ApiCobrancaWebhookRoute
  ApiDasGerarRoute: typeof ApiDasGerarRoute
  ApiSerproCallRoute: typeof ApiSerproCallRoute
  ApiSerproStatusRoute: typeof ApiSerproStatusRoute
  ApiUsuariosConvidarRoute: typeof ApiUsuariosConvidarRoute
  ApiWaInstancesRoute: typeof ApiWaInstancesRoute
  ApiWaSendRoute: typeof ApiWaSendRoute
  ApiWhatsappModoHumanoRoute: typeof ApiWhatsappModoHumanoRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiNfseIndexRoute: typeof ApiNfseIndexRoute
  ApiPublicEvolutionWebhookInstanceRoute: typeof ApiPublicEvolutionWebhookInstanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-dev': {
      id: '/login-dev'
      path: '/login-dev'
      fullPath: '/login-dev'
      preLoaderRoute: typeof LoginDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/societario': {
      id: '/_app/societario'
      path: '/societario'
      fullPath: '/societario'
      preLoaderRoute: typeof AppSocietarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obrigacoes': {
      id: '/_app/obrigacoes'
      path: '/obrigacoes'
      fullPath: '/obrigacoes'
      preLoaderRoute: typeof AppObrigacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dp': {
      id: '/_app/dp'
      path: '/dp'
      fullPath: '/dp'
      preLoaderRoute: typeof AppDpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos': {
      id: '/_app/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contabil': {
      id: '/_app/contabil'
      path: '/contabil'
      fullPath: '/contabil'
      preLoaderRoute: typeof AppContabilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automacoes': {
      id: '/_app/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/nfse/': {
      id: '/api/nfse/'
      path: '/api/nfse'
      fullPath: '/api/nfse/'
      preLoaderRoute: typeof ApiNfseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/fiscal/': {
      id: '/_app/fiscal/'
      path: '/fiscal'
      fullPath: '/fiscal/'
      preLoaderRoute: typeof AppFiscalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/modo-humano': {
      id: '/api/whatsapp/modo-humano'
      path: '/api/whatsapp/modo-humano'
      fullPath: '/api/whatsapp/modo-humano'
      preLoaderRoute: typeof ApiWhatsappModoHumanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa/send': {
      id: '/api/wa/send'
      path: '/api/wa/send'
      fullPath: '/api/wa/send'
      preLoaderRoute: typeof ApiWaSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa/instances': {
      id: '/api/wa/instances'
      path: '/api/wa/instances'
      fullPath: '/api/wa/instances'
      preLoaderRoute: typeof ApiWaInstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usuarios/convidar': {
      id: '/api/usuarios/convidar'
      path: '/api/usuarios/convidar'
      fullPath: '/api/usuarios/convidar'
      preLoaderRoute: typeof ApiUsuariosConvidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/serpro/status': {
      id: '/api/serpro/status'
      path: '/api/serpro/status'
      fullPath: '/api/serpro/status'
      preLoaderRoute: typeof ApiSerproStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/serpro/call': {
      id: '/api/serpro/call'
      path: '/api/serpro/call'
      fullPath: '/api/serpro/call'
      preLoaderRoute: typeof ApiSerproCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/das/gerar': {
      id: '/api/das/gerar'
      path: '/api/das/gerar'
      fullPath: '/api/das/gerar'
      preLoaderRoute: typeof ApiDasGerarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cobranca/webhook': {
      id: '/api/cobranca/webhook'
      path: '/api/cobranca/webhook'
      fullPath: '/api/cobranca/webhook'
      preLoaderRoute: typeof ApiCobrancaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cobranca/setup-webhook': {
      id: '/api/cobranca/setup-webhook'
      path: '/api/cobranca/setup-webhook'
      fullPath: '/api/cobranca/setup-webhook'
      preLoaderRoute: typeof ApiCobrancaSetupWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cobranca/regua': {
      id: '/api/cobranca/regua'
      path: '/api/cobranca/regua'
      fullPath: '/api/cobranca/regua'
      preLoaderRoute: typeof ApiCobrancaReguaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cobranca/emitir': {
      id: '/api/cobranca/emitir'
      path: '/api/cobranca/emitir'
      fullPath: '/api/cobranca/emitir'
      preLoaderRoute: typeof ApiCobrancaEmitirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/$id': {
      id: '/api/checkout/$id'
      path: '/api/checkout/$id'
      fullPath: '/api/checkout/$id'
      preLoaderRoute: typeof ApiCheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/fiscal/serpro': {
      id: '/_app/fiscal/serpro'
      path: '/fiscal/serpro'
      fullPath: '/fiscal/serpro'
      preLoaderRoute: typeof AppFiscalSerproRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/nfse': {
      id: '/_app/fiscal/nfse'
      path: '/fiscal/nfse'
      fullPath: '/fiscal/nfse'
      preLoaderRoute: typeof AppFiscalNfseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/das': {
      id: '/_app/fiscal/das'
      path: '/fiscal/das'
      fullPath: '/fiscal/das'
      preLoaderRoute: typeof AppFiscalDasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dp_/$empresaId': {
      id: '/_app/dp_/$empresaId'
      path: '/dp/$empresaId'
      fullPath: '/dp/$empresaId'
      preLoaderRoute: typeof AppDpEmpresaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes_/servicos': {
      id: '/_app/configuracoes_/servicos'
      path: '/configuracoes/servicos'
      fullPath: '/configuracoes/servicos'
      preLoaderRoute: typeof AppConfiguracoesServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes_/$id': {
      id: '/_app/clientes_/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/evolution-webhook/$instance': {
      id: '/api/public/evolution-webhook/$instance'
      path: '/api/public/evolution-webhook/$instance'
      fullPath: '/api/public/evolution-webhook/$instance'
      preLoaderRoute: typeof ApiPublicEvolutionWebhookInstanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContabilRoute: typeof AppContabilRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppDpRoute: typeof AppDpRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppObrigacoesRoute: typeof AppObrigacoesRoute
  AppSocietarioRoute: typeof AppSocietarioRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppConfiguracoesServicosRoute: typeof AppConfiguracoesServicosRoute
  AppDpEmpresaIdRoute: typeof AppDpEmpresaIdRoute
  AppFiscalDasRoute: typeof AppFiscalDasRoute
  AppFiscalNfseRoute: typeof AppFiscalNfseRoute
  AppFiscalSerproRoute: typeof AppFiscalSerproRoute
  AppFiscalIndexRoute: typeof AppFiscalIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContabilRoute: AppContabilRoute,
  AppCrmRoute: AppCrmRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppDpRoute: AppDpRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppObrigacoesRoute: AppObrigacoesRoute,
  AppSocietarioRoute: AppSocietarioRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppConfiguracoesServicosRoute: AppConfiguracoesServicosRoute,
  AppDpEmpresaIdRoute: AppDpEmpresaIdRoute,
  AppFiscalDasRoute: AppFiscalDasRoute,
  AppFiscalNfseRoute: AppFiscalNfseRoute,
  AppFiscalSerproRoute: AppFiscalSerproRoute,
  AppFiscalIndexRoute: AppFiscalIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginDevRoute: LoginDevRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  ApiCheckoutIdRoute: ApiCheckoutIdRoute,
  ApiCobrancaEmitirRoute: ApiCobrancaEmitirRoute,
  ApiCobrancaReguaRoute: ApiCobrancaReguaRoute,
  ApiCobrancaSetupWebhookRoute: ApiCobrancaSetupWebhookRoute,
  ApiCobrancaWebhookRoute: ApiCobrancaWebhookRoute,
  ApiDasGerarRoute: ApiDasGerarRoute,
  ApiSerproCallRoute: ApiSerproCallRoute,
  ApiSerproStatusRoute: ApiSerproStatusRoute,
  ApiUsuariosConvidarRoute: ApiUsuariosConvidarRoute,
  ApiWaInstancesRoute: ApiWaInstancesRoute,
  ApiWaSendRoute: ApiWaSendRoute,
  ApiWhatsappModoHumanoRoute: ApiWhatsappModoHumanoRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiNfseIndexRoute: ApiNfseIndexRoute,
  ApiPublicEvolutionWebhookInstanceRoute:
    ApiPublicEvolutionWebhookInstanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
